---
- name: Vault Demo
  hosts: all
  become: true
  vars_files: vars/secret.yml

  tasks:
    - name: Creating users from vault passwd file
      user:
        name: "{{ item.name }}"
        password: "{{ item.pw | password_hash('sha512') }}"
      with_items:
        - "{{ newusers }}"
