- name: test play
  hosts: localhost
  tasks:
    - name: add delegation host
      add_host:
        name: client02.local.com
        ansible_host: 192.168.0.7
        ansible_user: vibinm

    - name: echo Hello
      command: echo "Hello from {{ inventory_hostname }}"
      delegate_to: client02.local.com
      register: output

    - debug:
        msg: "{{ output.stdout }}"
